### List All Posts
GET http://localhost:8080/api/v1/blog/all
Accept: application/json

###

### Get Post By ID
GET http://localhost:8080/api/v1/blog/6
Accept: application/json

###
GET http://localhost:8080/api/v1/blog/urgent
Accept: application/json

### 
GET http://localhost:8080/api/v1/blog/done
Accept: application/json

### Create New Post
POST http://localhost:8080/api/v1/blog
Content-Type: application/json
token: 1

{
    "title": "Post Title",
    "content": "I need help with my kitchen.",
    "state": "urgent",
    "idTypePost": 1,
    "idPostRequest": null
}

###

### Create response to a post
POST http://localhost:8080/api/v1/blog
Content-Type: application/json
token: 3

{
    "title": "Son Post",
    "content": "OK.",
    "state": "New",
    "idTypePost": 1,
    "idPostRequest": 4
}

###

### Delete Post By ID
DELETE http://localhost:8080/api/v1/blog/5
Accept: application/json

###

### Mark Post As Done
PUT http://localhost:8080/api/v1/blog/2/done
Accept: application/json
token :1

###

### Mark Post As Urgent
PUT http://localhost:8080/api/v1/blog/7/urgent
Accept: application/json
token: 1

### Update Post by ID
PUT http://localhost:8080/api/v1/blog/7
Content-Type: application/json
Accept: application/json
token: 2

{
    "title": "Updated Title",
    "content": "Updated content for the blog post.",
    "state": "active",
    "idTypePost": 2,
    "idPostRequest": null
}