###
GET http://localhost:8080/api/v1/property/all
Accept: application/json
Token: 1

###
GET http://localhost:8080/api/v1/property/4
Accept: application/json
Token: 1

###
POST http://localhost:8080/api/v1/property
Content-Type: application/json

